name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: ["1.16"]
        swag: ["1.7.0"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Install swag
        run: |
          wget https://github.com/swaggo/swag/releases/download/v${{ matrix.swag }}/swag_${{ matrix.swag }}_Linux_x86_64.tar.gz
          mkdir download
          tar -zxvf swag_${{ matrix.swag }}_Linux_x86_64.tar.gz -C download
          sudo mv download/swag /usr/bin
          rm -rf swag_${{ matrix.swag }}_Linux_x86_64.tar.gz download
      - name: Build server
        run: make
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
